### ISSUE TITLE
Why is Mandarin not supported

### ISSUE THREAD

**Issue by House-Men** [hgneng/ekho-android-cantonese#2]

**Comment by hgneng** [comment]
Ekho TTS's quality is not good at all. Most Android device (inside China) has Mandarin TTS build-in. And you can also get Mandarin voice from Google TTS (outside China).

I maintain Ekho Cantonese TTS because there seems no free Cantonese voice available in the Android application market.

**Comment by House-Men** [comment]
@hgneng There are many TTS, but they all have their own characteristics, otherwise there would be no ekho engine.
There are many Mandarin TTS for Android, but there are few offline Mandarin that sound good, are open source, and have no background control updates.
I tried the following changes to play Mandarin, but it crashed on some content. Is it due to incomplete cache data in the (. voice/. index) file?

jni/jni/EkhoService.cpp  223 line change to gp_ekho->setVoice("Mandarin");
res/raw/ekhodata.zip->Cantonese files(.dict/.voice/.index) replace with linux ekho-9.0.tar.xz->Mandarin files(.dict/.voice/.index)

**Comment by hgneng** [comment]
Could you find out the text that can reproduce the crash issue?

Will the text also cause Cantonese crash?

**Comment by House-Men** [comment]
@hgneng The original Cantonese version has never crashed, but the modified Mandarin version will definitely crash in some content.
For example:
"一百二十三" will not crash
"1234" will not crash
"123" will crash
"测试1234" will not crash
"测试123" will crash
"测试." It won't crash but you can only hear the test
"测试.123" will not crash
The data files are copied from linux ekho-9.0.tar.xz, voice (2.43MB) index (16.28KB) are much smaller than the Cantonese version, so I suspect that the cache data file is incomplete.

**Comment by hgneng** [comment]
I will take a look at it next week and try to build a apk for Mandarin. Please be patient.

**Comment by hgneng** [comment]
We need to change CheckVoiceData.java to update resource files index:
```
$ git diff src/net/eguidedog/ekho/CheckVoiceData.java
diff --git a/src/net/eguidedog/ekho/CheckVoiceData.java b/src/net/eguidedog/ekho/CheckVoiceData.java
index 1d62312..8789756 100644
--- a/src/net/eguidedog/ekho/CheckVoiceData.java
+++ b/src/net/eguidedog/ekho/CheckVoiceData.java
@@ -47,9 +47,12 @@ public class CheckVoiceData extends Activity {

     /** Resources required for Ekho to run correctly. */
     private static final String[] BASE_RESOURCES = {
-        "zhy.dict",
-        "jyutping.index",
-        "jyutping.voice",
+            "zh.dict",
+            "pinyin.index",
+            "pinyin.voice",
+        //"zhy.dict",
+        //"jyutping.index",
+        //"jyutping.voice",
     };

     public static File getDataPath(Context context) {
```

**Comment by hgneng** [comment]
I've built one for you. Have a try: https://eguidedog.net/tmp/ekho-mandarin.apk

**Comment by House-Men** [comment]
@hgneng I changed it to the resource file name corresponding to Cantonese and replaced it. The resource should be loaded correctly. However, the Mandarin version you sent did not crash. It may be that the resource file name was not modified, which had any impact.
